name: Push Trigger Workflow

### Executa apenas em push
on:
  push:
    branches:
        - main
        - develop
    paths:
        - 'src/**' # CRIAR ESSES ARQUIVOS PARA FUNCIONAR
        - 'README.md' # CRIAR ESSES ARQUIVOS PARA FUNCIONAR

jobs:
    push-job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Informações do Push
              run: |
                echo "Workflow disparado por PUSH"
                echo "Branch: ${{ github.ref_name }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Repository: ${{ github.repository }}"
                echo "Pushed by: ${{ github.actor }}"
            
            - name: Listar arquivos modificados
              run: |
                echo "Arquivos no repositório:"
                ls -la
